pipeline {
    parameters {
        choice(name: 'terraformactions', choices: ['apply', 'destroy'], description: 'choose your terraform action')
    }

    environment {
        AWS_DEFAULT_REGION = 'us-east-1'
        AWS_ACCESS_KEY_ID = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
    }

    agent any

    stages{
        stage('checkout'){
            steps{
                script {
                    dir("terraform2"){ 
                        git branch: 'main',url:'https://github.com/Anup-cloud28/terraform2.git'
                    }
                }
            }
        }
    
        stage('Plan'){
            steps{
                // Navigate into the checked-out directory and then into the Project-1 subdirectory
                sh 'cd terraform2/project2; terraform init' 
                sh 'cd terraform2/project2; terraform plan -out tfplan'
                sh 'cd terraform2/project2; terraform show -no-color tfplan >> ../tfplan.txt' // Write plan to parent dir for easier access
            }
        }
    
        stage('approval'){
            steps{
                script {
                    // Read the plan file from the workspace root or the checked out directory (using iac-repo/tfplan.txt)
                    def plan = readFile 'terraform2/tfplan.txt'
                    
       
                    input(
                        message: "Do you want to proceed with terraform action..?",
                        parameters: [
                            text(name: 'planReview', description: 'Can you review your code one more time', defaultValue: plan)
                        ]
                    )
                }
            }
        }
    
        stage('Apply or Destroy'){
            when{
                expression{
                    return params.terraformAction == 'apply' || params.terraformAction == 'destroy'
                }
            }
    
            steps{
                script{
                    if (params.terraformAction == 'apply'){
                     
                        sh "cd terraform2/project2; terraform apply -input=false tfplan" 
                    } else if(params.terraformAction == 'destroy'){
                 
                        sh "cd terraform2/project2; terraform destroy -auto-approve" 
                    }
                }
            }
        }
    }
}